//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.23 at 11:04:04 AM BST 
//


package com.bbc.JavaTest.HelloWorld;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RunParameters">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ServerConnect" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DatabaseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AssetsPath_WS-MANLON" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ValidateSchema" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="CopyAssets" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="OverwriteAudioItem" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "runParameters"
})
@XmlRootElement(name = "ImportDiraConfig")
public class ImportDiraConfig {

    @XmlElement(name = "RunParameters", required = true)
    protected ImportDiraConfig.RunParameters runParameters;

    /**
     * Gets the value of the runParameters property.
     * 
     * @return
     *     possible object is
     *     {@link ImportDiraConfig.RunParameters }
     *     
     */
    public ImportDiraConfig.RunParameters getRunParameters() {
        return runParameters;
    }

    /**
     * Sets the value of the runParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportDiraConfig.RunParameters }
     *     
     */
    public void setRunParameters(ImportDiraConfig.RunParameters value) {
        this.runParameters = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ServerConnect" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DatabaseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AssetsPath_WS-MANLON" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ValidateSchema" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="CopyAssets" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="OverwriteAudioItem" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serverConnect",
        "databaseName",
        "assetsPathWSMANLON",
        "validateSchema",
        "copyAssets",
        "overwriteAudioItem"
    })
    public static class RunParameters {

        @XmlElement(name = "ServerConnect", required = true)
        protected String serverConnect;
        @XmlElement(name = "DatabaseName", required = true)
        protected String databaseName;
        @XmlElement(name = "AssetsPath_WS-MANLON", required = true)
        protected String assetsPathWSMANLON;
        @XmlElement(name = "ValidateSchema")
        protected boolean validateSchema;
        @XmlElement(name = "CopyAssets")
        protected boolean copyAssets;
        @XmlElement(name = "OverwriteAudioItem")
        protected boolean overwriteAudioItem;

        /**
         * Gets the value of the serverConnect property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerConnect() {
            return serverConnect;
        }

        /**
         * Sets the value of the serverConnect property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerConnect(String value) {
            this.serverConnect = value;
        }

        /**
         * Gets the value of the databaseName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatabaseName() {
            return databaseName;
        }

        /**
         * Sets the value of the databaseName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatabaseName(String value) {
            this.databaseName = value;
        }

        /**
         * Gets the value of the assetsPathWSMANLON property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssetsPathWSMANLON() {
            return assetsPathWSMANLON;
        }

        /**
         * Sets the value of the assetsPathWSMANLON property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssetsPathWSMANLON(String value) {
            this.assetsPathWSMANLON = value;
        }

        /**
         * Gets the value of the validateSchema property.
         * 
         */
        public boolean isValidateSchema() {
            return validateSchema;
        }

        /**
         * Sets the value of the validateSchema property.
         * 
         */
        public void setValidateSchema(boolean value) {
            this.validateSchema = value;
        }

        /**
         * Gets the value of the copyAssets property.
         * 
         */
        public boolean isCopyAssets() {
            return copyAssets;
        }

        /**
         * Sets the value of the copyAssets property.
         * 
         */
        public void setCopyAssets(boolean value) {
            this.copyAssets = value;
        }

        /**
         * Gets the value of the overwriteAudioItem property.
         * 
         */
        public boolean isOverwriteAudioItem() {
            return overwriteAudioItem;
        }

        /**
         * Sets the value of the overwriteAudioItem property.
         * 
         */
        public void setOverwriteAudioItem(boolean value) {
            this.overwriteAudioItem = value;
        }

    }

}
